"""market data: candles, option contracts, option candles

Revision ID: 323f5b753c2c
Revises: a1b2c3d4e5f6
Create Date: 2026-09-02 20:11:04.317287
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '323f5b753c2c'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_candles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('exchange', sa.String(length=8), nullable=False),
    sa.Column('interval', sa.String(length=12), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('oi', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'exchange', 'interval', 'timestamp', name='uq_market_candle_symbol_exch_interval_ts')
    )
    with op.batch_alter_table('market_candles', schema=None) as batch_op:
        batch_op.create_index('ix_market_candle_symbol_ts', ['symbol', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_candles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_candles_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_candles_timestamp'), ['timestamp'], unique=False)

    op.create_table('option_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('underlying', sa.String(length=24), nullable=False),
    sa.Column('exchange', sa.String(length=8), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_token', sa.String(length=64), nullable=True),
    sa.Column('symbol', sa.String(length=80), nullable=False),
    sa.Column('expiry', sa.Date(), nullable=False),
    sa.Column('strike', sa.Float(), nullable=False),
    sa.Column('option_type', sa.String(length=2), nullable=False),
    sa.Column('lot_size', sa.Integer(), nullable=True),
    sa.Column('tick_size', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_token', name='uq_option_contract_provider_token'),
    sa.UniqueConstraint('symbol', name='uq_option_contract_symbol'),
    sa.UniqueConstraint('underlying', 'exchange', 'expiry', 'strike', 'option_type', name='uq_option_contract_natural_key')
    )
    with op.batch_alter_table('option_contracts', schema=None) as batch_op:
        batch_op.create_index('ix_option_contract_underlying_expiry', ['underlying', 'expiry'], unique=False)
        batch_op.create_index(batch_op.f('ix_option_contracts_expiry'), ['expiry'], unique=False)
        batch_op.create_index(batch_op.f('ix_option_contracts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_option_contracts_underlying'), ['underlying'], unique=False)

    op.create_table('option_candles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('oi', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['option_contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id', 'timestamp', name='uq_option_candle_contract_ts')
    )
    with op.batch_alter_table('option_candles', schema=None) as batch_op:
        batch_op.create_index('ix_option_candle_contract_ts', ['contract_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_option_candles_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_option_candles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_option_candles_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('option_candles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_option_candles_timestamp'))
        batch_op.drop_index(batch_op.f('ix_option_candles_id'))
        batch_op.drop_index(batch_op.f('ix_option_candles_contract_id'))
        batch_op.drop_index('ix_option_candle_contract_ts')

    op.drop_table('option_candles')
    with op.batch_alter_table('option_contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_option_contracts_underlying'))
        batch_op.drop_index(batch_op.f('ix_option_contracts_id'))
        batch_op.drop_index(batch_op.f('ix_option_contracts_expiry'))
        batch_op.drop_index('ix_option_contract_underlying_expiry')

    op.drop_table('option_contracts')
    with op.batch_alter_table('market_candles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_candles_timestamp'))
        batch_op.drop_index(batch_op.f('ix_market_candles_symbol'))
        batch_op.drop_index(batch_op.f('ix_market_candles_id'))
        batch_op.drop_index('ix_market_candle_symbol_ts')

    op.drop_table('market_candles')
    # ### end Alembic commands ###
